name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: testing_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pre-commit Checks
        uses: pre-commit/action@v3.0.0

      - name: Python Setup
        uses: actions/setup-python@v4

      - name: Install iac-validate
        run: pip install iac-validate

      - name: Run Yamale check
        run: yamale -s schema.yaml nxos_model.yaml

      - name: Run iac-validate checks
        run: iac-validate -r rules nxos_model.yaml 
