name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: testing_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-commit Checks
        uses: pre-commit/action@v3.0.1

      - name: Python Setup
        uses: actions/setup-python@v5

      - name: Install iac-validate
        run: pip install 'iac-validate>=0.1.4'

      - name: Run iac-validate
        run: iac-validate -s schema.yaml -r rules nxos_model_example.yaml
